# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: scottkw.StorCat
PackageVersion: 2.1.0
InstallerType: nullsoft
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/scottkw/storcat/releases/download/v2.1.0/StorCat-v2.1.0-windows-amd64-installer.exe
  InstallerSha256: 0000000000000000000000000000000000000000000000000000000000000000
ManifestType: installer
ManifestVersion: 1.6.0
