// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {config} from '../models';

export function BrowseCatalogs(arg1:string):Promise<Array<models.CatalogMetadata>>;

export function CreateCatalog(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.CreateCatalogResult>;

export function GetCatalogHtmlPath(arg1:string):Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetVersion():Promise<string>;

export function GetWindowPersistence():Promise<boolean>;

export function LoadCatalog(arg1:string):Promise<models.CatalogItem>;

export function OpenExternal(arg1:string):Promise<void>;

export function ReadHtmlFile(arg1:string):Promise<string>;

export function SearchCatalogs(arg1:string,arg2:string):Promise<Array<models.SearchResult>>;

export function SelectDirectory():Promise<string>;

export function SetSidebarPosition(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetWindowPersistence(arg1:boolean):Promise<void>;

export function SetWindowPosition(arg1:number,arg2:number):Promise<void>;

export function SetWindowSize(arg1:number,arg2:number):Promise<void>;
