// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseCatalogs(arg1) {
  return window['go']['main']['App']['BrowseCatalogs'](arg1);
}

export function CreateCatalog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateCatalog'](arg1, arg2, arg3, arg4);
}

export function GetCatalogHtmlPath(arg1) {
  return window['go']['main']['App']['GetCatalogHtmlPath'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWindowPersistence() {
  return window['go']['main']['App']['GetWindowPersistence']();
}

export function LoadCatalog(arg1) {
  return window['go']['main']['App']['LoadCatalog'](arg1);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function ReadHtmlFile(arg1) {
  return window['go']['main']['App']['ReadHtmlFile'](arg1);
}

export function SearchCatalogs(arg1, arg2) {
  return window['go']['main']['App']['SearchCatalogs'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetSidebarPosition(arg1) {
  return window['go']['main']['App']['SetSidebarPosition'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetWindowPersistence(arg1) {
  return window['go']['main']['App']['SetWindowPersistence'](arg1);
}

export function SetWindowPosition(arg1, arg2) {
  return window['go']['main']['App']['SetWindowPosition'](arg1, arg2);
}

export function SetWindowSize(arg1, arg2) {
  return window['go']['main']['App']['SetWindowSize'](arg1, arg2);
}
