// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {config} from '../models';
import {volumes} from '../models';
import {main} from '../models';

export function BrowseCatalogs(arg1:string):Promise<Array<models.CatalogMetadata>>;

export function CancelScan():Promise<void>;

export function CreateCatalog(arg1:string,arg2:string,arg3:string,arg4:string):Promise<models.CreateCatalogResult>;

export function DeleteCatalog(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function DuplicateCatalog(arg1:string,arg2:string):Promise<string>;

export function GetCatalogHtmlPath(arg1:string,arg2:string):Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetVersion():Promise<string>;

export function GetWindowPersistence():Promise<boolean>;

export function ListVolumes():Promise<Array<volumes.Volume>>;

export function LoadCatalog(arg1:string):Promise<models.CatalogItem>;

export function LoadCatalogFlat(arg1:string):Promise<models.FlatCatalog>;

export function OpenExternal(arg1:string,arg2:string):Promise<void>;

export function ReadHtmlFile(arg1:string):Promise<string>;

export function RenameCatalog(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RevealInFileManager(arg1:string,arg2:string):Promise<void>;

export function SearchCatalogs(arg1:string,arg2:string):Promise<Array<models.SearchResult>>;

export function SearchIndexed(arg1:string,arg2:string):Promise<models.SearchIndexResult>;

export function SelectDirectory():Promise<string>;

export function SetCatalogDirectory(arg1:string):Promise<void>;

export function SetCopyToSecondary(arg1:boolean):Promise<void>;

export function SetDefaultFilenameRoot(arg1:string):Promise<void>;

export function SetDensity(arg1:string):Promise<void>;

export function SetRailSide(arg1:string):Promise<void>;

export function SetSecondaryDirectory(arg1:string):Promise<void>;

export function SetSettingsMigrated(arg1:boolean):Promise<void>;

export function SetSidebarPosition(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetWatchDirectory(arg1:boolean):Promise<void>;

export function SetWindowPersistence(arg1:boolean):Promise<void>;

export function SetWindowPosition(arg1:number,arg2:number):Promise<void>;

export function SetWindowSize(arg1:number,arg2:number):Promise<void>;

export function SetWriteHTML(arg1:boolean):Promise<void>;

export function StartScan(arg1:string,arg2:string,arg3:string,arg4:string,arg5:main.ScanOptions):Promise<models.CreateCatalogResult>;

export function WritePartialCatalog():Promise<models.CreateCatalogResult>;
