// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseCatalogs(arg1) {
  return window['go']['main']['App']['BrowseCatalogs'](arg1);
}

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function CreateCatalog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateCatalog'](arg1, arg2, arg3, arg4);
}

export function GetCatalogHtmlPath(arg1, arg2) {
  return window['go']['main']['App']['GetCatalogHtmlPath'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWindowPersistence() {
  return window['go']['main']['App']['GetWindowPersistence']();
}

export function ListVolumes() {
  return window['go']['main']['App']['ListVolumes']();
}

export function LoadCatalog(arg1) {
  return window['go']['main']['App']['LoadCatalog'](arg1);
}

export function LoadCatalogFlat(arg1) {
  return window['go']['main']['App']['LoadCatalogFlat'](arg1);
}

export function OpenExternal(arg1, arg2) {
  return window['go']['main']['App']['OpenExternal'](arg1, arg2);
}

export function ReadHtmlFile(arg1) {
  return window['go']['main']['App']['ReadHtmlFile'](arg1);
}

export function RenameCatalog(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameCatalog'](arg1, arg2, arg3);
}

export function RevealInFileManager(arg1, arg2) {
  return window['go']['main']['App']['RevealInFileManager'](arg1, arg2);
}

export function SearchCatalogs(arg1, arg2) {
  return window['go']['main']['App']['SearchCatalogs'](arg1, arg2);
}

export function SearchIndexed(arg1, arg2) {
  return window['go']['main']['App']['SearchIndexed'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetCatalogDirectory(arg1) {
  return window['go']['main']['App']['SetCatalogDirectory'](arg1);
}

export function SetCopyToSecondary(arg1) {
  return window['go']['main']['App']['SetCopyToSecondary'](arg1);
}

export function SetDefaultFilenameRoot(arg1) {
  return window['go']['main']['App']['SetDefaultFilenameRoot'](arg1);
}

export function SetDensity(arg1) {
  return window['go']['main']['App']['SetDensity'](arg1);
}

export function SetRailSide(arg1) {
  return window['go']['main']['App']['SetRailSide'](arg1);
}

export function SetSecondaryDirectory(arg1) {
  return window['go']['main']['App']['SetSecondaryDirectory'](arg1);
}

export function SetSettingsMigrated(arg1) {
  return window['go']['main']['App']['SetSettingsMigrated'](arg1);
}

export function SetSidebarPosition(arg1) {
  return window['go']['main']['App']['SetSidebarPosition'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetWatchDirectory(arg1) {
  return window['go']['main']['App']['SetWatchDirectory'](arg1);
}

export function SetWindowPersistence(arg1) {
  return window['go']['main']['App']['SetWindowPersistence'](arg1);
}

export function SetWindowPosition(arg1, arg2) {
  return window['go']['main']['App']['SetWindowPosition'](arg1, arg2);
}

export function SetWindowSize(arg1, arg2) {
  return window['go']['main']['App']['SetWindowSize'](arg1, arg2);
}

export function SetWriteHTML(arg1) {
  return window['go']['main']['App']['SetWriteHTML'](arg1);
}

export function StartScan(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartScan'](arg1, arg2, arg3, arg4, arg5);
}

export function WritePartialCatalog() {
  return window['go']['main']['App']['WritePartialCatalog']();
}
